"""Value-free node runtime bindings sourced from generated-artifact outputs.

Split from ``runtime_configuration`` (issue #1074): a node's runtime environment
may source a value from a ``generated_artifacts[].outputs`` entry instead of a
literal. The reference carries no bytes - the raw value is realized at
provisioning time - so these models stay a small, self-contained subdomain that
both the environment surface and the stateful-resource reference validator reuse.
"""

from __future__ import annotations

from pydantic import Field

from ._base import SDLModel
from ._identifiers import PortableIdentifier
from .stateful_resources import (
    GeneratedArtifact,
    GeneratedArtifactOutput,
    GeneratedArtifactOutputDisposition,
    ResourceSensitivity,
)


class GeneratedArtifactValueSource(SDLModel):
    """Value-free reference to a generated-artifact output consumed as a runtime value.

    Names the producing ``generated_artifacts.<id>`` (bare id or namespaced
    form) and one of its outputs. It carries no generated bytes: the raw value
    is realized at provisioning time from the referenced output, never authored
    into the SDL. Cross-resource resolution (artifact exists, output exists and
    is not ``producer_private``) is enforced by semantic admission.
    """

    generated_artifact: str = Field(min_length=1)
    output: PortableIdentifier


class RuntimeEnvironmentFile(SDLModel):
    """A node runtime env-file delivered from a generated-artifact output.

    The file is an opaque generated-artifact output projected as one runtime
    environment input; RAES does not parse or compare its individual key/value
    entries. Authors declare the binding here, on the node, not as a fake
    variable name and not as an ordinary read-only file mount.

    ``name`` is a bounded portable identity, not a filesystem path: the compiler
    forwards it as the env-file target in the provisioning projection, so it must
    not admit path traversal, newlines, or shell metacharacters that could
    redirect the generated secret outside the runtime env-file namespace.
    """

    name: PortableIdentifier
    value_from: GeneratedArtifactValueSource
    description: str = ""


def resolve_consumable_generated_artifact_output(
    artifact: GeneratedArtifact,
    output_name: str,
    *,
    environment_classification: object | None = None,
) -> GeneratedArtifactOutput:
    """Resolve one consumer-visible output and enforce its disclosure contract."""

    output = next((candidate for candidate in artifact.outputs if candidate.name == output_name), None)
    if output is None:
        raise ValueError(f"selects unknown generated artifact output {output_name!r}")
    if output.disposition is GeneratedArtifactOutputDisposition.PRODUCER_PRIVATE:
        raise ValueError("cannot consume a producer_private generated artifact output")
    classification = getattr(environment_classification, "value", environment_classification)
    if (
        output.sensitivity is ResourceSensitivity.SECRET
        and environment_classification is not None
        and classification != "redacted"
    ):
        raise ValueError("generated secret output requires redacted runtime environment classification")
    return output


def value_from_schema_exclusions() -> list[dict[str, object]]:
    """Published-schema ``allOf`` constraints for the env-var value_from exclusions.

    Encodes, for schema-only consumers, the same cross-field rules the Python
    model enforces (issue #1074): a ``value_from`` reference may not ride with a
    literal ``value``, and a generated-artifact value may not claim the
    out-of-SDL ``operator_secret`` classification.
    """

    return [
        {
            "not": {
                "allOf": [
                    {
                        "required": ["value_from"],
                        "properties": {"value_from": {"not": {"type": "null"}}},
                    },
                    {"required": ["value"], "properties": {"value": {"minLength": 1}}},
                ]
            }
        },
        {
            "not": {
                "allOf": [
                    {
                        "required": ["value_from"],
                        "properties": {"value_from": {"not": {"type": "null"}}},
                    },
                    {
                        "required": ["value_classification"],
                        "properties": {"value_classification": {"const": "operator_secret"}},
                    },
                ]
            }
        },
    ]


__all__ = [
    "GeneratedArtifactValueSource",
    "RuntimeEnvironmentFile",
    "resolve_consumable_generated_artifact_output",
    "value_from_schema_exclusions",
]
