#!/usr/bin/env python3
from __future__ import annotations

import argparse
import sys
import tempfile
from hashlib import sha256
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
SCHEMAS_ROOT = REPO_ROOT / "contracts" / "schemas"
PYTHON_ROOT = REPO_ROOT / "implementations" / "python"


def parse_args() -> argparse.Namespace:
    return argparse.ArgumentParser(
        description=(
            "Prove the reference implementation generates schemas identical to the published "
            "normative contracts under contracts/schemas/ (ADR-009 section 7). The published "
            "schemas are the authority; this check generates into a throwaway directory and never "
            "overwrites them."
        )
    ).parse_args()


def _snapshot_schema_tree(root: Path) -> dict[str, str]:
    snapshot: dict[str, str] = {}
    for path in sorted(root.rglob("*.json")):
        snapshot[path.relative_to(root).as_posix()] = sha256(path.read_bytes()).hexdigest()
    return snapshot


def _extra_published_schema_paths(root: Path, *, expected_relative_paths: set[str]) -> list[str]:
    published = {path.relative_to(root).as_posix() for path in sorted(root.rglob("*.json"))}
    return sorted(published - expected_relative_paths)


def main() -> int:
    parse_args()

    if str(REPO_ROOT) not in sys.path:
        sys.path.insert(0, str(REPO_ROOT))
    for python_path in (PYTHON_ROOT / "src", PYTHON_ROOT / "packages"):
        python_path_str = str(python_path)
        if python_path_str not in sys.path:
            sys.path.insert(0, python_path_str)
    from tools.generate_contract_schemas import write_schema_bundle

    # ADR-009 section 7: contracts/schemas/ is the hand-governed normative
    # authority. Generate the reference implementation's bundle into a throwaway
    # directory and prove it matches the published authority — never overwrite
    # the published schemas, or the compatibility proof would silently mutate the
    # source of truth it is meant to verify.
    published = _snapshot_schema_tree(SCHEMAS_ROOT)
    with tempfile.TemporaryDirectory() as tmp_dir:
        generated_root = Path(tmp_dir)
        write_schema_bundle(generated_root)
        generated = _snapshot_schema_tree(generated_root)

    drifted = sorted(rel_path for rel_path, digest in generated.items() if published.get(rel_path) != digest)
    extra_paths = _extra_published_schema_paths(SCHEMAS_ROOT, expected_relative_paths=set(generated))

    if drifted:
        print(
            "Reference implementation output drifted from the published normative schemas "
            "(ADR-009 section 7: contracts/schemas/ is the authority; the reference implementation "
            "proves compatibility). Update the reference implementation (schema_bundle()) to match "
            "the published schemas, or — if the contract itself is changing — edit the published "
            "schema and record a manifest ledger entry. Schemas that do not match:",
            file=sys.stderr,
        )
        for path in drifted:
            print(f"  - contracts/schemas/{path}", file=sys.stderr)
        return 1
    if extra_paths:
        print(
            "Published normative schemas are not generated by the reference implementation bundle; "
            "the reference implementation must generate every published normative schema:",
            file=sys.stderr,
        )
        for path in extra_paths:
            print(f"  - contracts/schemas/{path}", file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
