"""Completion metadata for SDL language-service helpers."""

from __future__ import annotations

REFERENCE_COMPLETION_TARGETS = {
    ("nodes", "features"): "features",
    ("nodes", "conditions"): "conditions",
    ("nodes", "injects"): "injects",
    ("nodes", "vulnerabilities"): "vulnerabilities",
    ("infrastructure", "links"): "infrastructure",
    ("infrastructure", "dependencies"): "infrastructure",
    ("features", "dependencies"): "features",
    ("events", "conditions"): "conditions",
    ("events", "injects"): "injects",
    ("scripts", "events"): "events",
    ("stories", "scripts"): "scripts",
    ("content", "target"): "nodes",
    ("accounts", "node"): "nodes",
    ("relationships", "source"): "any",
    ("relationships", "target"): "any",
    ("agents", "entity"): "entities",
    ("agents", "starting_accounts"): "accounts",
    ("behavior_specifications", "participant_refs"): "agents",
    ("behavior_specifications", "action_contract_refs"): "action_contracts",
    ("behavior_specifications", "observation_boundary_refs"): "observation_boundaries",
    ("behavior_specifications", "outcome_interpretation_rule_refs"): "outcome_interpretation_rules",
    ("behavior_specifications", "authority_scope_refs"): "any",
    ("evidence_requirements", "source_refs"): "any",
    ("evidence_requirements", "scope_refs"): "any",
    ("evidence_requirements", "channel_refs"): "any",
    ("evidence_requirements", "trigger_ref"): "any",
    ("evidence_requirements", "boundary_ref"): "any",
    ("objectives", "agent"): "agents",
    ("objectives", "entity"): "entities",
    ("objectives", "targets"): "any",
    ("objectives", "depends_on"): "objectives",
    ("injects", "from_entity"): "entities",
    ("injects", "to_entities"): "entities",
    ("workflows", "start"): "workflow_steps",
}

SECTION_FIELD_COMPLETIONS = {
    "nodes": ("type", "description", "os", "resources", "features", "conditions", "services", "roles"),
    "infrastructure": ("count", "links", "dependencies", "properties"),
    "features": ("type", "source", "version", "dependencies"),
    "conditions": ("command", "interval", "description"),
    "vulnerabilities": ("name", "description", "technical", "class"),
    "entities": ("name", "role", "facts", "entities"),
    "injects": ("source", "from_entity", "to_entities"),
    "events": ("conditions", "injects"),
    "scripts": ("start_time", "end_time", "speed", "events"),
    "stories": ("speed", "scripts"),
    "content": ("type", "target", "format", "source", "path", "items"),
    "accounts": ("username", "node", "password_strength"),
    "relationships": ("type", "source", "target", "properties"),
    "agents": ("entity", "actions", "starting_accounts", "initial_knowledge"),
    "behavior_specifications": (
        "semantic_version",
        "lifecycle_state",
        "participant_refs",
        "participant_role_refs",
        "action_contract_refs",
        "observation_boundary_refs",
        "outcome_interpretation_rule_refs",
        "authority_scope_refs",
        "behavior_mode",
        "ai_offensive_behavior_refs",
        "offensive_behavior_refs",
        "realization_profile_ref",
        "backend_feature_support_refs",
        "evidence_contract_refs",
        "extension_policy",
        "extensions",
    ),
    "evidence_requirements": (
        "source_refs",
        "source_class",
        "scope_refs",
        "scope",
        "window",
        "trigger_ref",
        "boundary_ref",
        "boundary_kind",
        "channel",
        "channel_refs",
        "artifact_role",
        "media_types",
        "sensitivity",
        "redaction",
        "integrity",
        "retention",
        "loss_disclosure",
    ),
    "objectives": ("agent", "entity", "actions", "targets", "success", "window", "depends_on"),
    "workflows": ("start", "steps"),
    "variables": ("type", "default", "required", "allowed_values", "description"),
}
